### ISSUE TITLE
Crashes on first preview attempt, fine after restarting

### ISSUE THREAD

**Issue by canguroenglish** [xupefei/QuickLook#1018]
Since upgrading to 3.7.0 my installation always seems to crash on the first preview attempt of any file type, but then when I restart the app it seems fine (although have noticed some lag in general compared to previous version). Looking at my crash logs they are always the same issue:

`System.ArgumentOutOfRangeException: Index was out of range. Must be non-negative and less than the size of the collection.`

Here is my latest full log:
```
========15/10/2021 13:39:19========
System.ArgumentOutOfRangeException: Index was out of range. Must be non-negative and less than the size of the collection.
Parameter name: index
   at System.ThrowHelper.ThrowArgumentOutOfRangeException(ExceptionArgument argument, ExceptionResource resource)
   at System.Collections.Generic.List`1.RemoveAt(Int32 index)
   at System.Windows.Media.Composition.DUCE.Map.Remove(Object key)
   at System.Windows.Media.Composition.DUCE.MultiChannelResource.ReleaseOnChannel(Channel channel)
   at System.Windows.Media.HostVisual.Disconnect(Channel channel, Dispatcher channelDispatcher, ResourceHandle hostHandle, ResourceHandle targetHandle, MultiChannelResource contentRoot)
   at System.Windows.Media.HostVisual.DoPendingDisconnect(Channel channel)
   at System.Windows.Media.HostVisual.DoDisconnectHostedVisual(Object arg)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.DispatcherOperation.InvokeImpl()
   at System.Windows.Threading.DispatcherOperation.InvokeInSecurityContext(Object state)
   at MS.Internal.CulturePreservingExecutionContext.CallbackWrapper(Object obj)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at MS.Internal.CulturePreservingExecutionContext.Run(CulturePreservingExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Windows.Threading.DispatcherOperation.Invoke()
   at System.Windows.Threading.Dispatcher.ProcessQueue()
   at System.Windows.Threading.Dispatcher.WndProcHook(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, Object args, Int32 numArgs)
   at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam)
   at MS.Win32.UnsafeNativeMethods.DispatchMessage(MSG& msg)
   at System.Windows.Threading.Dispatcher.PushFrameImpl(DispatcherFrame frame)
   at System.Windows.Threading.Dispatcher.PushFrame(DispatcherFrame frame)
   at System.Windows.Application.RunDispatcher(Object ignore)
   at System.Windows.Application.RunInternal(Window window)
   at System.Windows.Application.Run(Window window)
   at QuickLook.App.Main()
```
OS Version: Windows 10 Pro 10.0.19043 Build 19043
QuickLook Version: 3.7.0 from github msi

Before the upgrade I hadn't had a crash in over a year. I hope that helps!

p.s. your app is amazing and has saved me thousands of hours!

**Comment by canguroenglish** [comment]
> Sounds like a duplicate of #1004.

Could be, but mine is on any file type, not just WAVs.
