### ISSUE TITLE
Error with Files associated with LibreOffice

### ISSUE THREAD

**Issue by Raggedy-Man** [xupefei/QuickLook#296]
*You can use either Chinese or English when filling this issue. 你可以使用中文或英语填写以下问题。*

**Describe the bug**

**To Reproduce**
Pressing Space on Word/Excel Documents with LibreOffice Installed produces error "Failed to Preview File"

**Expected behavior**
Show File Details ( As, there is no support for LibreOffice )

**Desktop (please complete the following information):**
 - OS Version: Windows 10 1803
 - QuickLook Version: 0.3.5 msi 

**Screenshots and Exception Log**
Screenshot:
![image](https://user-images.githubusercontent.com/23501700/42724647-e0bca17a-8793-11e8-95a0-078e34eddb8a.png)

Log:
========14-07-2018 06:23:02 PM========
System.Runtime.InteropServices.COMException (0x80040154): Retrieving the COM class factory for component with CLSID {00020827-0000-0000-C000-000000000046} failed due to the following error: 80040154 Class not registered (Exception from HRESULT: 0x80040154 (REGDB_E_CLASSNOTREG)).
   at System.RuntimeTypeHandle.CreateInstance(RuntimeType type, Boolean publicOnly, Boolean noCheck, Boolean& canBeCached, RuntimeMethodHandleInternal& ctor, Boolean& bNeedSecurityCheck)
   at System.RuntimeType.CreateInstanceSlow(Boolean publicOnly, Boolean skipCheckThis, Boolean fillCache, StackCrawlMark& stackMark)
   at System.Activator.CreateInstance(Type type, Boolean nonPublic)
   at System.Activator.CreateInstance(Type type)
   at QuickLook.Plugin.IPreviewHandlers.PreviewHandlerHost.Open(String path)
   at QuickLook.Plugin.IPreviewHandlers.Plugin.View(String path, ContextObject context)
   at QuickLook.ViewerWindow.<>c__DisplayClass6_0.<BeginShow>b__0()

========14-07-2018 06:23:22 PM========
System.Runtime.InteropServices.COMException (0x80040154): Retrieving the COM class factory for component with CLSID {84F66100-FF7C-4FB4-B0C0-02CD7FB668FE} failed due to the following error: 80040154 Class not registered (Exception from HRESULT: 0x80040154 (REGDB_E_CLASSNOTREG)).
   at System.RuntimeTypeHandle.CreateInstance(RuntimeType type, Boolean publicOnly, Boolean noCheck, Boolean& canBeCached, RuntimeMethodHandleInternal& ctor, Boolean& bNeedSecurityCheck)
   at System.RuntimeType.CreateInstanceSlow(Boolean publicOnly, Boolean skipCheckThis, Boolean fillCache, StackCrawlMark& stackMark)
   at System.Activator.CreateInstance(Type type, Boolean nonPublic)
   at System.Activator.CreateInstance(Type type)
   at QuickLook.Plugin.IPreviewHandlers.PreviewHandlerHost.Open(String path)
   at QuickLook.Plugin.IPreviewHandlers.Plugin.View(String path, ContextObject context)
   at QuickLook.ViewerWindow.<>c__DisplayClass6_0.<BeginShow>b__0()

**Comment by xupefei** [comment]
00020827-0000-0000-C000-000000000046 is the CLSID for MS Word. Do you have Office installed?

**Comment by Raggedy-Man** [comment]
I am using LibreOffice. Previously, the file info would pop-up ( as it does with executable files ) without the error, but recently this error started to happen.

**Comment by xupefei** [comment]
It's because you have recently installed and then uninstalled MS Office. Please follow the guide here: https://support.microsoft.com/en-gb/help/3100511/this-file-cannot-be-previewed-because-there-is-no-previewer-installed, and be sure to stop at Step 5, i.e., delete the key.

**Comment by Raggedy-Man** [comment]
Thanks! I really appreciate you helping me out here. Would be really glad if you could add support for LibreOffice too.

**Comment by xupefei** [comment]
I would like to, but it's not depend on me 😀
LibreOffice need to provide some way to allow that.

Cheers,
Paddy

**Comment by vivadavid** [comment]
Hello!

I was wondering if, since your last message, LibreOffice has made the implementation of a plugin any easier. Is there a way we could make a proper request? Perhaps via the LibreOffice forum.
